//! Caddyfile generation from app records.

use std::fmt::Write as _;

use crate::app::AppRecord;

/// Renders a Caddyfile for generated + preview + custom hostnames.
#[must_use]
pub fn render(apps: &[AppRecord], loom_api: &str) -> String {
    let mut out = String::from("# generated by loomd — do not edit\n");
    let _ = write!(out, "{loom_api} {{\n    reverse_proxy loomd:8080\n}}\n");
    for app in apps {
        for env in app.environments.values() {
            if env.hostname.is_empty() {
                continue;
            }
            let upstream = format!("{}-{}:8080", app.id.replace('/', "-"), env.name);
            let _ = write!(
                out,
                "{} {{\n    reverse_proxy {upstream}\n}}\n",
                env.hostname
            );
        }
    }
    out
}
